services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --enable-source-maps
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: octocat
      MYSQL_DATABASE: value
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/src

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: octocat
      MYSQL_DATABASE: value
      TZ: UTC
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db: