services:
  dev:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ../..:/workspaces:cached   
    network_mode: service:db
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: octocat
      MYSQL_DATABASE: value

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: octocat
      MYSQL_DATABASE: value
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  db: