services:
  dev:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:mongo
    command: sleep infinity
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PORT: 8080
      NODE_ENV: development
      MONGODB_URI: mongodb://root:octocat@mongo:27017

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: octocat
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "root", "-p", "octocat", "--authenticationDatabase", "admin"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mongo-data:
