name: Docker Deploy GHCR

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_call:
    inputs:
      artifact-name:
        default: "dist"
        required: false
        type: string
    outputs:
      tags:
        description: "The first output string"
        value: ${{ jobs.docker-ghcr.outputs.tags }}
      labels:
        description: "The first output string"
        value: ${{ jobs.docker-ghcr.outputs.labels }}

jobs:
  docker-ghcr:
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    environment:
      name: GitHub Container Registry
      url: https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/pkgs/container/${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,format=long
          images: ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max