name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/eslint
        with:
          working-directory: ./backend
          category: backend
      - uses: ./.github/actions/eslint
        with:
          working-directory: ./frontend
          category: frontend